#plain (default) plain
#solarized-dark solarized-dark
#solarized-light solarized-light
#slick slick
#modern modern
#bad-wolf bad-wolf
#gruvbox-light gruvbox-light
#gruvbox-dark gruvbox-dark
#space-villain space-villain
#native (like plain with no background and native separators) native
#semi-native (like native but with background) //TODO add an image
#nord-dark (polar night) nord-dark
#dracula

[theme]
theme = "ctp-latte"
[theme.overrides]
idle_bg = "#eff1f5"
#idle_fg = "#000000"
[icons]
icons = "awesome4"
[icons.overrides]
music = ""

#[[block]]
#block = "focused_window"

[[block]]
block = "music"
#player = "spotify"
#format = "  $title.str(max_w:100)"
[block.theme_overrides]
idle_bg = "#cbcfd9"
#idle_fg = "#111111"
info_bg = "#444444"
#info_fg = "#111111"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"
format = " $icon "
[block.theme_overrides]
idle_bg = "#cbcfd9"
#idle_fg = "#111111"

[[block]]
block = "cpu"
interval = 1
format = " $icon $frequency.eng(prefix:M,w:3)@$utilization "

#[[block]]
#block = "xrandr"
#format = "$icon $resolution"

[[block]]
block = "temperature"
interval = 1
#format = "{max}|{average}"
format_alt = " $icon $max/$average "
format = " $icon "
[block.theme_overrides]
#info_bg = "#eeeeee"
#info_fg = "#111111"

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:3) "
[block.theme_overrides]
idle_bg = "#cbcfd9"
#idle_fg = "#111111"

# County code
[[block]]
block = "custom"
command = """curl -s http://ip-api.com/json |  grep -o '"countryCode": *"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"'"""
interval = 40
[block.theme_overrides]
idle_bg = "#1aba8f"
idle_fg = "#eeeeee"

# Windscribe Data Usage
#[[block]]
#block = "custom"
#command = """windscribe account | sed -n '3p' | grep -o -P '(?<=: ).*(?= /)'"""
#interval = 40
#[block.theme_overrides]
#idle_bg = "#709acf"
#idle_fg = "#eeeeee"

[[block]]
block = "memory"
format = " $icon $mem_used "
#format = " $icon$mem_used/$mem_total "
# format = "$icon$mem_used/$mem_avail"

[[block]]
block = "disk_space"
path = "/"
info_type = "free"
interval = 5
alert = 50.0
format = " $icon $available "
[block.theme_overrides]
#idle_bg = "#eeeeee"
#idle_fg = "#111111"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
format = " $icon $percentage $time $power "
[block.theme_overrides]
good_bg = "#1aba8f"
#good_fg = "#111111"

#[[block]]
#block = "kdeconnect"
#format = " $icon $bat_charge "

[[block]]
block = "uptime"

[[block]]
block = "net"
# format = " $icon $speed_down \uF175 /$speed_up \uF176 " 
format = " $icon @$ssid " 
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "weather"
format = " $icon $temp "
# format = "$icon $weather ($location) $temp, $wind m/s $direction"
service = { name = "openweathermap", api_key = "17e96788a74ed298f5b9706c6e6509e6", city_id = "2529013", units = "metric" }
[block.theme_overrides]
idle_bg = "#cbcfd9"

[[block]]
block = "time"
interval = 60
[block.format]
full = "  $timestamp.datetime(f:'%d/%m', l:en_US) "

[[block]]
block = "time"
interval = 1
[block.format]
full = "  $timestamp.datetime(f:'%I:%M:%S%P', l:en_US) "

##[[block]]
##block = "custom"
##interval = 999999
##command = "echo '\uF011'"
##on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"
